#config_version=6

mode:
  start_events: ball_started
  stop_events: end_skillshot, skill_shot_unlit_hit, timer_skillshot_complete
  priority: 1020

shot_profiles: 
  skillshot:
    states: 
     - name: unlit
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     - name: flashing
       show: flash_color
       loops: -1
       speed: 4
       sync_ms: 250
       show_tokens: 
         color: FFFFFF
     - name: flashing_super
       show: flash_color
       loops: -1
       speed: 4
       sync_ms: 0
       show_tokens: 
         color: FFFF00

shots: 
  skill_lane1:
    switch: sw65
    show_tokens: 
      lights: bonus_lane1
    advance_events: mode_skillshot_started
    profile: skillshot
  skill_lane2:
    switch: sw73
    show_tokens: 
      lights: bonus_lane2
    profile: skillshot
  skill_lane3:
    switch: sw48
    show_tokens: 
      lights: bonus_lane3
    profile: skillshot
  skill_leftramp:
    switch: sw85
    show_tokens: 
      lights: left_ramp
    profile: skillshot
    control_events: 
      - events: mode_skillshot_started
        state: 2

shot_groups: 
  skill_shot:
    shots: skill_lane1,skill_lane2,skill_lane3
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active

event_player: 
  skill_leftramp_flashing_super_hit: 
    - award_super_skillshot
    - end_skillshot|3s
  skill_shot_flashing_hit: 
    - award_skillshot
    - end_skillshot|3s

variable_player:
  award_skillshot:
    score: 100000
  award_super_skillshot:
    score: 250000

slide_player:
  award_skillshot:
    skillshot_overlay:
      expire: 3s

sound_player:
  award_skillshot: skillshot
  debug: true