#config_version=6

mode:
  start_events: trigger_race2
  stop_events: timer_race2_complete, ball_ended
  priority: 1005

shot_profiles: 
  race2_profile:
    advance_on_hit: false
    states: 
     - name: flashing
       show: flash_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ff0000

shots: 
  race2_leftramp:
    switch: sw80
    show_tokens: 
      lights: left_ramp
    profile: race2_profile
  race2_rightramp:
    switch: sw82
    show_tokens: 
      lights: right_ramp
    profile: race2_profile

shot_groups:
  race_2:
    shots: race2_leftramp, race2_rightramp
    restart_events: mode_race_2_started

timers:
  race2:
    start_running: true
    tick_interval: 1s
    end_value: 30
    restart_on_complete: no
    control_events:
      - event: mode_race_2_started
        action: restart
      - event: mode_race_2_stopped
        action: stop

event_player: 
  mode_race_2_started: 
    - race_started
  ball_ending: 
    - race_ended
  mode_race_1_stopping:
    - race_ended

variable_player:
  race_2_hit:
    score: 1000000

show_player:
  race_2_hit: 
    sweep_up:
      loops: 0
      speed: 4

slide_player:
  mode_race_2_starting:
    race1_selection:
      action: remove
    race2_selection:
      action: remove
    race3_selection:
      action: remove

light_player:
  mode_race_2_started:
    T_GI: 
        color: FF0000