#config_version=6
  
light_player:
  mode_attract_started: 
   insert: FFFFFF
   T_GI: FF0000
   
slide_player:
  mode_attract_started: attract
  timer_attract_overlay_tick{ticks==3}: attract_overlay
  timer_attract_overlay_complete:
    attract_overlay:
      action: remove

timers:
  attract_overlay:
    end_value: 6
    start_running: true
    restart_on_complete: true
