#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 1400

shot_profiles: 
  qualify_emp:
    advance_on_hit: false
    states: 
     - name: lit
       show: led_color
       show_tokens: 
         color: FFFFFF
       loops: -1
       speed: 1
       sync_ms: 0

shots: 
  emp_pop1:
    switch: s_bumper_1
    show_tokens: 
      lights: bumper1
    profile: qualify_emp
  emp_pop2:
    switch: s_bumper_2
    show_tokens: 
      lights: bumper2
    profile: qualify_emp

show_player:
  emp_pop1_hit: 
    flash_color:
      show_tokens:
        lights: bumper1
        color: FF00FF
      speed: 4
      loops: 0