#config_version=6

mode:
  start_events: ball_started, mode_emp_hurry_stopped
  stop_events: ball_ended, trigger_emp_hurry
  priority: 1400

shot_profiles: 
  qualify_emp:
    advance_on_hit: false
    states: 
     - name: lit
       show: led_color
       show_tokens: 
         color: FFFFFF
       loops: -1
       speed: 1
       sync_ms: 0

shots: 
  emp_pop1:
    switch: s_bumper_1
    show_tokens: 
      lights: bumper1
    profile: qualify_emp
  emp_pop2:
    switch: s_bumper_2
    show_tokens: 
      lights: bumper2
    profile: qualify_emp
  emp_pop3:
    switch: s_bumper_3
    show_tokens: 
      lights: bumper3
    profile: qualify_emp

shot_groups:
  qualify_emp:
    shots: emp_pop1, emp_pop2, emp_pop3
    restart_events: mode_qualify_emp_started

show_player:
  emp_pop1_hit: 
    flash_color:
      show_tokens:
        lights: bumper1
        color: FF00FF
      speed: 4
      loops: 0
  emp_pop2_hit: 
    flash_color:
      show_tokens:
        lights: bumper2
        color: FF00FF
      speed: 4
      loops: 0
  emp_pop3_hit: 
    flash_color:
      show_tokens:
        lights: bumper3
        color: FF00FF
      speed: 4
      loops: 0

event_player:
  qualify_emp_hit{current_player.emp_hits == 20}: trigger_emp_hurry

variable_player:
  qualify_emp_hit:
    score: 25000
    emp_hits: 1
  mode_qualify_emp_started:
    emp_hits: 0
    action: set