#config_version=6

mode:
  start_events: race_selection_confirmed{current_player.player_shot_rs1_tri==1}
  stop_events: timer_race1_complete, ball_ended
  priority: 1005

shot_profiles: 
  race_profile:
    advance_on_hit: false
    states: 
     - name: flashing
       show: flash_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ff0000

shots: 
  race1_leftorbit:
    switch: sw08
    show_tokens: 
      lights: left_orbit
    profile: race_profile
  race1_rightorbit:
    switch: sw81
    show_tokens: 
      lights: right_orbit
    profile: race_profile

shot_groups:
  race_1:
    shots: race1_leftorbit, race1_rightorbit
    restart_events: mode_race_1_started

timers:
  race1:
    start_running: true
    tick_interval: 1s
    end_value: 30
    restart_on_complete: no
    control_events:
      - event: mode_race_1_started
        action: restart
      - event: mode_race_1_stopped
        action: stop

event_player: 
  mode_race_1_started: 
    - race_started
  ball_ending: 
    - mode_race_ended

variable_player:
  race_1_hit:
    score: 100000

show_player:
  race_1_hit: 
    sweep_up:
      loops: 0
      speed: 4

