#config_version=6

player_vars:
  lock_hits:
    initial_value: 3
  lock_l:
    initial_value: ""
    value_type: str
  lock_o:
    initial_value: ""
    value_type: str
  lock_c:
    initial_value: ""
    value_type: str
  lock_k:
    initial_value: ""
    value_type: str
  lock_activations:
    initial_value: 0
  boost_activations:
    initial_value: 1
    value_type: int
  jackpot_value:
    initial_value: 2500000
  jackpot_boost_value:
    initial_value: 0
  bonusX:
    initial_value: 1
  bonus_races:
    initial_value: 0
  bonus_combos:
    initial_value: 0
  bonus_nodes:
    initial_value: 0