#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

modes:
  - attract
  - base

hardware:
  platform: virtual
  rgb_dmd: pin2dmd

bcp:
  connections:
	local_display:
	  host: localhost #192.168.86.25
	  port: 5050
  debug: true

pin2dmd:
  resolution: 256x64
  panel: rgb

rgb_dmds:
  default:
	hardware_brightness: 0.9
	source_display: main
	fps: 30
	only_send_changes: true
