#config_version=6

mode:
  start_events: multiball_bridge_started
  stop_events: multiball_bridge_ended
  priority: 1310

shots:
  multiball_bottom_spinner:
    switch: sw98
    profile: multiball_jackpots
    show_tokens: 
      lights: spinner_bottom
  multiball_left_orbit:
    switch: sw41
    profile: multiball_jackpots
    show_tokens: 
      lights: left_orbit
  multiball_left_ramp:
    switch: sw85
    profile: multiball_jackpots
    show_tokens: 
      lights: left_ramp
  multiball_right_ramp:
    switch: sw86
    profile: multiball_jackpots
    show_tokens: 
      lights: right_ramp
  multiball_right_orbit:
    switch: sw81
    profile: multiball_jackpots
    show_tokens: 
      lights: right_orbit
  multiball_top_spinner:
    switch: sw99
    profile: multiball_jackpots
    show_tokens: 
      lights: spinner_top

shot_profiles:
  multiball_jackpots:
    states:
      - name: flashing
        show: flash_color
        loops: -1
        speed: 4
        sync_ms: 0
        show_tokens: 
          color: 00FF00
      - name: off
        show: off
        loops: -1
        sync_ms: 0

# Group for completion detection + reset on mode start
shot_groups:
  multiball_shots:
    shots: multiball_bottom_spinner, multiball_left_orbit, multiball_left_ramp, multiball_right_ramp, multiball_right_orbit, multiball_top_spinner
    reset_events: multiball_super_hit, multiball_shots_complete

slide_player:
  multiball_shots_flashing_hit:
    multiball_jackpot:
      expire: 2

# ----- SCORING & LOGIC -----
variable_player:
  multiball_shots_flashing_hit:
    score: current_player.jackpot_value + current_player.jackpot_boost_value