#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 1000

ball_saves: 
  base:
    active_time: 10s
    grace_period: 3s
    hurry_up_time: 5s
    enable_events: mode_base_started
    timer_start_events: balldevice_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: -1

show_player: 
  ball_save_base_timer_start: 
    flash_color: 
      key: ball_save
      speed: 2
      show_tokens: 
        lights: ball_save
        color: CC33FF
  ball_save_base_hurry_up: 
    flash_color: 
      key: ball_save
      speed: 4
      show_tokens: 
        lights: ball_save
        color: CC33FF
  ball_save_base_grace_period: 
    flash_color: 
      action: stop
      key: ball_save


light_player: 
  mode_base_started: 
    T_GI: 
      color: FFFFFF

slide_player:
  mode_base_started: base


variable_player:
  s_bumper_1_active:
    score: 1000
  s_bumper_2_active:
    score: 1000
  s_bumper_3_active:
    score: 1000
  s_left_sling_active:
    score: 1000
  s_right_sling_active:
    score: 1000
